[[extensions]]
name = "send-invoice"
handle = "send-invoice"
type = "flow_action"

description = "Your description"
runtime_url = "https://shopify-app-ten-pi.vercel.app/flow-action/handle"

[settings]

  [[settings.fields]]
  type = "order_reference"
  required = true
  
  [[settings.fields]]
  type = "customer_reference"
  required = true

  [[settings.fields]]
  type = "single_line_text_field"
  key = "your-field-key"
  name = "Display name"
  description = "A description of my field"
  required = true
